# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29d16ea6d73a2a79977f2e526783b47a5078973f368775e27301be12bd092a5ce0b1bb9caa7293ac7030345161212f209a4d94aa17872923279984995df7502e

test:
  secret_key_base: 35569e3ece370c39a55a64414e894dc098cbd1525e8f7e8f3f9263f084a7419f56f40c02dcd9c6f290b3c6982b8efb8ad9d8020c509fbc5f0da5ff0252139908

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
